feat: add role to credential and proof record
openwallet-foundation/credo-ts pull request #1764
Opened 2024-02-14 12:31 UTC by berendsliedrecht

Signed-off-by: Timo Glastra <timo@animo.id>

2024-02-15 01:46 UTC, TimoGlastra requested changes
It's not really updated for 0.5

2024-02-15 01:46 UTC, TimoGlastra commented on packages/anoncreds-rs/tests/anoncreds-flow.test.ts
> +describeRunInNodeVersion([18], 'AnonCreds format services using anoncreds-rs', () => {
Is this a new test? Probably added with merge conflicts?

2024-02-15 01:46 UTC, TimoGlastra commented on packages/anoncreds/src/updates/0.3.1-0.4/__tests__/credentialExchangeRecord.test.ts
> +  describe('migrateRole()', () => {
This should be moved to 0.5 migration

2024-02-15 01:46 UTC, TimoGlastra commented on packages/anoncreds/src/updates/0.3.1-0.4/__tests__/proofExchangeRecord.test.ts
> +const agentConfig = getAgentConfig('AnonCreds Migration - Proof Exchange Record - 0.3.1-0.4.0')
Same, should be 0.5

2024-02-15 01:46 UTC, TimoGlastra commented on packages/anoncreds/src/updates/0.3.1-0.4/__tests__/proofExchangeRecord.test.ts
> +  })
This is not testing state done, which was still a fixme in the previous PR. I think same for credential

2024-02-15 01:46 UTC, TimoGlastra commented on packages/anoncreds/src/updates/0.3.1-0.4/credentialExchangeRecord.ts
> +  })
There can be multiple didcomm message records retuned for this. Will be good to add a full test that reaches this code with an actual database populated in 0.4 and migrating it to 0.5

2024-02-15 01:46 UTC, TimoGlastra commented on packages/anoncreds/src/updates/0.3.1-0.4/credentialExchangeRecord.ts
> +    // Check whether the role of the didcomm message is `receiver`
This logic doesn't make sense. we should fetch a specific didcomm message record.

2024-02-15 01:46 UTC, TimoGlastra commented on packages/anoncreds/src/updates/0.3.1-0.4/credentialExchangeRecord.ts
> +      if (didCommCredentialIssuerAsSenderRoles.includes(credentialRecord.state)) {
In all cases except done we can extract the role based on state, so this feels a bit redundant.
We can just check on the offer message, if role == sender, we're role = issuer else role = holder.

Might need to handle the case where there's only a proposal or only a request (if state is abandoned)

2024-02-19 12:35 UTC, berendsliedrecht commented
Not entirely sure why tests are failing on the `agent.config`...

https://github.com/openwallet-foundation/credo-ts/actions/runs/7958832675/job/21724520202?pr=1764#step:5:675

2024-02-20 14:33 UTC, berendsliedrecht commented
Might need some help with setting up new snapshots :).

2024-02-26 05:32 UTC, TimoGlastra commented
> Might need some help with setting up new snapshots :).

Did you already address this? Anything I can help with?

2024-02-28 14:44 UTC, TimoGlastra approved these changes

2024-02-28 14:45 UTC, TimoGlastra commented
Should be ready now @berendsliedrecht

2024-02-29 05:18 UTC, merged