fix: process problem report message
openwallet-foundation/credo-ts pull request #1859
Opened 2024-05-08 14:21 UTC by sairanjit

### Summary

Fixes #1858

2024-05-08 16:02 UTC, TimoGlastra requested changes

2024-05-08 16:02 UTC, TimoGlastra commented on packages/core/src/modules/credentials/protocol/BaseCredentialProtocol.ts
>      })
This is dangerous as it allows anyone to send a response to the credential exchange by knowing the thread id. For this reason we don't support problem reports currently for connectionsless exchanges.

If we want to support this, we need to handle it the same as is done in the processRequest message. Which consists of:
- query the record without connection id
- then if the record has a connection id:
  - check if it matches the connection id from the exchange
- if the record does not have a connection id:
  - check that the problem report is authorized based on the out of band exchange (the parentThreadId also need to match)
  - if the incoming message has a connection associated, update the connectionId in the exchange record

This is already implemented like this for processRequest, and I think you can copy most of the logic

2024-05-08 17:25 UTC, TimoGlastra commented
Hmm it seems there's a small issue with the logic (not from your code. I'll push some changes to this PR tomorrow to fix that as well)

2024-05-09 05:34 UTC, TimoGlastra commented
Pushed some changes @sairanjit

2024-05-09 06:51 UTC, sairanjit commented
@TimoGlastra I removed this check 
```typescript
const connection = messageContext.assertReadyConnection()
```
As it was failing for connection less flows

2024-06-04 08:26 UTC, TimoGlastra approved these changes

2024-06-04 08:26 UTC, merged