chore: updating dependabot file to support GHA, TS, JS, dev container and docker packages
openwallet-foundation/credo-ts pull request #1881
Opened 2024-05-27 18:21 UTC by rajpalc7

2024-05-27 18:21 UTC, rajpalc7 commented
Hi @WadeBarnes , this is ready for review now.

2024-05-27 19:07 UTC, WadeBarnes approved these changes
LGTM, but I'll leave the final review and approval to the regular maintainers.

2024-05-30 06:57 UTC, genaris requested changes
Thanks @rajpalc7 ! Could you fix the prettier errors? It can be done by running `yarn format`.

2024-06-04 08:46 UTC, TimoGlastra requested changes
Can we make sure to group all the dependencies into one PR? I'm really overwhelmed by the 100s of dependabot PR notifications I have to deal with on a daily basis and it distracts from more meaningful PRs

Also -- can we configure it to only make __patch__ updates for production dependencies? I'm not really intersted in updates for dev-deps and would rather update these manually once in a while.

Also -- is there a way to fully automate the merging of patches if the CI succeeds?

2025-01-23 06:18 UTC, closed without merging