feat: add pagination params to storage service
openwallet-foundation/credo-ts pull request #1883
Opened 2024-05-28 01:37 UTC by mrlunin

This is mainly an implementation for #1007.

Aries Askar supports pagination using offset and limit, so I added additional parameters `$offset` and `$limit` (with `$` to not overlap with some existing record tags) to the Storage service and added implementation to AskarStorageService.

I added this because we have server deployment and to avoid querying all records at once.

2024-05-28 07:16 UTC, TimoGlastra requested changes
I like the simplicity of the solution, but i don't think it should be added as tags. But rather as separate options

2024-05-28 12:00 UTC, genaris commented on packages/core/src/storage/StorageService.ts
> +interface PaginationQuery {
I agree with @TimoGlastra in that maybe using an extra query options parameters would be cleaner. What about something like the following?

```ts
export type QueryOptions = {
  limit?: number
  offset?: number
}

findByQuery(agentContext: AgentContext, recordClass: BaseRecordConstructor<T>, query: Query<T>, queryOptions?: QueryOptions): Promise<T[]>
```

2024-06-10 08:32 UTC, mrlunin commented
@TimoGlastra @genaris I've added an additional parameter `QueryOptions` to the `findByQuery`. Can you check the code?

2024-06-10 08:41 UTC, TimoGlastra approved these changes
I like it! Thanks @mrlunin 🙏

2024-06-10 19:46 UTC, TimoGlastra commented
There's several tests failing @mrlunin, if you address these we can merge this :)

2024-06-12 08:30 UTC, merged